### ISSUE TITLE
Does not accept arrays for params and result

### ISSUE THREAD

**Issue by lugrinder** [osamingo/jsonrpc#5]
As denoted in JSON-RPC 2.0 Specifications, request 'params' and response 'result' can be object or array, and now only accepts objects.

**Comment by osamingo** [comment]
@lugrinder Hi, Could you show me a source (e.g. URL) this issue?

**Comment by lugrinder** [comment]
Hi, sorry a mistake by my part while defining parameters. It works fine..

**Comment by osamingo** [comment]
@lugrinder No problem :) Thanks for using my library!
